FROM ubuntu:latest

ENV EDITOR vim
ENV SHELL bash

# setup to add bitcoin repository
RUN apt-get -q update && apt-get install software-properties-common --no-install-recommends -y -q && add-apt-repository ppa:bitcoin/bitcoin

RUN apt-get -q update && apt-get upgrade -y && apt-get install --no-install-recommends -y -q \
	build-essential \
	libtool \
	autotools-dev \
	automake \
	pkg-config \
	libssl-dev \
	libevent-dev \
	bsdmainutils \
	python3 \
	libboost-system-dev \
	libboost-filesystem-dev \
	libboost-chrono-dev \
	libboost-program-options-dev \
	libboost-test-dev \
	libboost-thread-dev \
	libqt5gui5 \
	libqt5core5a \
	libqt5dbus5 \
	qttools5-dev \
	qttools5-dev-tools \
	libprotobuf-dev \
	protobuf-compiler \
	miniupnpc \
	vim \
	libdb4.8-dev \
	libdb4.8++-dev \
	libdb4.8 \
	git \
	libzmq3-dev \
	libevent-2.1-6 \
	curl \
	htop 

# Pull the ravencoin distribution
RUN mkdir -p /Ravencoin && git clone https://github.com/RavenProject/Ravencoin.git /Ravencoin 

# Build the software
RUN cd /Ravencoin && ./autogen.sh && ./configure && make && make install && rm -rf /Ravencoin

# Adding the user to the image 
RUN useradd -s /bin/bash -m /var/lib/rvn rvn
RUN chown rvn:rvn -R /var/lib/rvn

#Volume
VOLUME ["/home/rvn/raven"]

# node service
EXPOSE 8767
